farmer/cart/urls.py
from django.urls import path

from . import views

app_name = "cart"

urlpatterns = [
    path("", views.cart_detail, name="cart_detail"),
    path("add/<int:product_id>/", views.cart_add, name="cart_add"),
    path("remove/<int:product_id>/", views.cart_remove, name="cart_remove"),
]

farmer/chat/urls.py
from django.urls import path

from . import views

app_name = "chat"


urlpatterns = [
    path("room/<int:user1_id>/<int:user2_id>/", views.chat, name="chat_room"),
    path("rooms/<int:user1_id>", views.chat_rooms, name="list_rooms"),
]

farmer/farmer/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from . import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("store/", include("store.urls", namespace="store")),
    path("users/", include("users.urls", namespace="users")),
    path("cart/", include("cart.urls", namespace="cart")),
    path("order/", include("order.urls", namespace="order")),
    path("chat/", include("chat.urls", namespace="chat")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

farmer/chat/models.py
"""
Модуль содержит два класса: ChatRoom и ChatMessage.
Оба класса отвечают за моделирование данных, используемых в чат-приложении
"""
from django.contrib.auth.models import User
from django.db import models


class ChatRoom(models.Model):
    """моделирует комнату чата между двумя пользователями"""

    buyer = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="buyer_chat_rooms"
    )
    seller = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="seller_chat_rooms"
    )
    seller_unread_messages_count = models.PositiveIntegerField(default=0)
    buyer_unread_messages_count = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f"{self.buyer.username}'s chat with {self.seller.username}"

    def update_unread_messages_count(self, user):
        """обновление счетчика непрочитанных сообщений"""
        if self.buyer == user:
            self.seller_unread_messages_count += 1
        elif self.seller == user:
            self.buyer_unread_messages_count += 1
        self.save()

    def clean_unread_messages_count(self, user):
        """сбрасывание счетчика непрочитанных сообщений"""
        if self.seller == user:
            self.seller_unread_messages_count = 0
        elif self.buyer == user:
            self.buyer_unread_messages_count = 0
        self.save()


class ChatMessage(models.Model):
    """моделирует сообщения, отправляемые в чате"""

    chat_room = models.ForeignKey(
        ChatRoom, on_delete=models.CASCADE, related_name="chat_messages"
    )
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="buyer_chat_messages"
    )

    message = models.TextField(blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return (
            f"{self.chat_room.buyer.username}'s chat with {self.chat_room.seller.username}: {self.message}"
        )

farmer/chat/forms.py
""""""

farmer/chat/views.py
"""Модуль chat содержит две функции: chat() и chat_rooms().

Функция chat() создает новую комнату чата или подключается к
существующей комнате между двумя пользователями и возвращает шаблон
chat.html с сообщениями чата, относящимися к данной комнате.

Функция chat_rooms() отображает список комнат чата для данного
пользователя и возвращает шаблон rooms.html с объектом пользователя и
списком чат-комнат, в которых участвует пользователь в качестве продавца
или покупателя.
"""

from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpRequest, HttpResponse
from django.shortcuts import get_object_or_404, render

from .models import ChatMessage, ChatRoom


@login_required(login_url="users:login")
def chat(request: HttpRequest, user1_id: int, user2_id: int) -> HttpResponse:
    """Создание и подключение к чату."""
    # получаем объекты пользователей или возвращаем 404 ошибку, если не существуют
    user1 = get_object_or_404(User, id=user1_id)
    user2 = get_object_or_404(User, id=user2_id)
    # получаем объект чат-комнаты или создаем новый, если не существует
    chatroom, created = ChatRoom.objects.get_or_create(
        seller=user1, buyer=user2)
    # получаем сообщения чата, относящиеся к данной комнате и сортируем по времени
    messages = ChatMessage.objects.filter(
        chat_room=chatroom.id).order_by("timestamp")

    return render(
        request,
        "chat/chat.html",
        {
            "user1": user1,
            "user2": user2,
            "messages": messages,
        },
    )


@login_required(login_url="users:login")
def chat_rooms(request: HttpRequest, user1_id: int) -> HttpResponse:
    """Отображает список комнат для данного пользователя."""
    # получаем объект пользователя или возвращаем 404 ошибку, если не существует
    user1 = get_object_or_404(User, id=user1_id)
    # получаем чат-комнаты, в которых участвует данный пользователь в качестве продавца или покупателя
    if user1.groups.filter(name="Sellers").exists():
        chatrooms = ChatRoom.objects.filter(seller=user1)
    else:
        chatrooms = ChatRoom.objects.filter(buyer=user1)

    return render(
        request,
        "chat/rooms.html",
        {
            "user1": user1,
            "chatrooms": chatrooms,
        },
    )

farmer/chat/templates/chat/chat.html
{% extends "store/base.html" %}

{% block title %}Chat room {% endblock %}
{% block header %}{% endblock %}
{% block content %}
  <div id="chat">
    {% for message in messages %}
    
      {% if message.user == request.user %}
      <div class="message me">
        <strong>Me</strong>:
        <span>{{ message.message }}</span>
        <span class="date">{{ message.created_at }}</span>
      </div>
      {% else %}
      <div class="message">
        <strong>{{message.user.username}}</strong>:
        <span>{{ message.message }}</span>
        <span class="date">{{ message.created_at }}</span>
      </div>
      {% endif%}
    
    {% endfor %}
  </div>
  <div id="chat-input">
    <input id="chat-message-input" type="text">
    <input id="chat-message-submit" type="submit" value="Send">
  </div>
{% endblock %}



{% block include_js %}
  {{ user1.id|json_script:"user-1" }}
  {{ user2.id|json_script:"user-2" }}
  {{ request.user.username|json_script:"request-user" }}
{% endblock %}

{% block domready %}
  const user1_Id = JSON.parse(
    document.getElementById('user-1').textContent
  );
  const user2_Id = JSON.parse(
    document.getElementById('user-2').textContent
  );
  const requestUser = JSON.parse(
    document.getElementById('request-user').textContent
  );
  const url = 'ws://' + window.location.host +
            '/ws/chat/' + user1_Id + '/' + user2_Id + '/';
  const chatSocket = new WebSocket(url);

  chatSocket.onmessage = function(event) {
    const data = JSON.parse(event.data);
    const chat = document.getElementById('chat');

    const dateOptions = {hour: 'numeric', minute: 'numeric', hour12: true};
    const datetime = new Date(data.datetime).toLocaleString('en', dateOptions);
    const isMe = data.user === requestUser;
    const source = isMe ? 'me' : 'other';
    const name = isMe ? 'Me' : data.user;

    chat.innerHTML += '<div class="message ' + source + '">' +
                      '<strong>' + name + '</strong> ' +
                      '<span class="date">' + datetime + '</span><br>' +
                      data.message + '</div>';
    chat.scrollTop = chat.scrollHeight;
  };

  chatSocket.onclose = function(event) {
    console.error('Chat socket closed unexpectedly');
  };

  const input = document.getElementById('chat-message-input');
  const submitButton = document.getElementById('chat-message-submit');



  submitButton.addEventListener('click', function(event) {
    const message = input.value;
    if(message) {
      // send message in JSON format
      chatSocket.send(JSON.stringify({'message': message}));
      // clear input
      input.value = '';
      input.focus();
    }
  });

  input.addEventListener('keypress', function(event) {
    if (event.key === 'Enter') {
      // cancel the default action, if needed
      event.preventDefault();
      // trigger click event on button
      submitButton.click();
    }
  });

  input.focus();
{% endblock %}

farmer/chat/templates/chat/rooms.html
{% extends "store/base.html" %}
{% block title %}Rooms{% endblock %}
{% block content %}
{% for  room in chatrooms %}
    <ul>
    <li><a href="{% url 'chat:chat_room' room.seller.id room.buyer.id %}">{{ room }}</a></li>
    {% if request.user.is_staff %}
    <p>{{room.seller_unread_messages_count}}</p>
    {% else%}
    <p>{{room.buyer_unread_messages_count}}</p>
    {% endif %}
    
    </ul>
{% endfor %}
{% endblock %}