farmer/cart/urls.py
from django.urls import path

from . import views

app_name = "cart"

urlpatterns = [
    path("", views.cart_detail, name="cart_detail"),
    path("add/<int:product_id>/", views.cart_add, name="cart_add"),
    path("remove/<int:product_id>/", views.cart_remove, name="cart_remove"),
]

farmer/farmer/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from . import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("store/", include("store.urls", namespace="store")),
    path("users/", include("users.urls", namespace="users")),
    path("cart/", include("cart.urls", namespace="cart")),
    path("order/", include("order.urls", namespace="order")),
    path("chat/", include("chat.urls", namespace="chat")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

farmer/store/urls.py
from django.urls import path

from . import views

app_name = "store"
urlpatterns = [
    path("", views.home, name="home"),
    path("like/", views.product_like, name="like"),
    path("rating/", views.rating, name="rating"),
    path("search/", views.Search.as_view(), name="search"),
    
    path("profile/<int:id>/", views.sellerprofile, name="profile"),
    path("<slug:category_slug>/", views.home, name="product_list_by_category"),
    path("<slug:slug>/<int:id>/", views.product_detail, name="product_detail"),
    path(
        "<slug:slug>/<int:id>/comment/",
        views.CommentCreateView.as_view(),
        name="comment-add",
    ),
    path(
        "comment/<int:pk>/update",
        views.CommentUpdateView.as_view(),
        name="comment-update",
    ),
    path(
        "comment/<int:pk>/delete/",
        views.CommentDeleteView.as_view(),
        name="comment-delete",
    ),
]

farmer/store/models.py
from typing import Optional

from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class Category(models.Model):
    """Категория товара."""

    name: str = models.CharField(max_length=100)
    slug: str = models.SlugField(max_length=100, unique=True)

    class Meta:
        verbose_name_plural: str = "Categories"
        verbose_name: str = "Category"
        ordering: list = ["name"]
        indexes: list = [
            models.Index(fields=["name"]),
        ]

    def get_absolute_url(self) -> str:
        """Метод для получения URL страницы списка товаров, относящихся к
        данной категории."""
        return reverse("store:product_list_by_category", args=[self.slug])

    def __str__(self) -> str:
        return self.name


class Product(models.Model):
    """Товар в магазине."""

    category: Category = models.ForeignKey(Category, on_delete=models.CASCADE)
    seller: User = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        editable=False,
        related_name="seller_products",
    )
    name: str = models.CharField(max_length=100)
    price: float = models.DecimalField(max_digits=10, decimal_places=2)
    slug: str = models.SlugField(max_length=100)
    description: Optional[str] = models.TextField(blank=True, null=True)
    image: Optional[models.ImageField] = models.ImageField(
        upload_to="images/products/", blank=True, null=True
    )
    available: bool = models.BooleanField(default=True)
    created_at: models.DateTimeField = models.DateTimeField(auto_now_add=True)
    updated_at: models.DateTimeField = models.DateTimeField(auto_now=True)
    users_like: models.ManyToManyField = models.ManyToManyField(
        User, related_name="products_liked", blank=True, editable=False
    )
    total_likes: int = models.IntegerField(default=0, editable=False)

    class Meta:
        ordering: list = ["name"]
        verbose_name_plural: str = "Products"
        verbose_name: str = "Product"
        indexes: list = [
            models.Index(fields=["name"]),
            models.Index(fields=["id", "slug"]),
        ]

    def save(self, *args, **kwargs) -> None:
        """Переопределение метода сохранения объекта.

        Если это новый объект, то устанавливает продавца товара из
        переданных параметров или текущего пользователя.
        """
        if not self.pk:
            self.seller = (
                self.seller or kwargs.pop(
                    "seller", None) or User.objects.get(pk=1)
            )
            # попытаться установить `seller` из self.seller или из переданных kwargs
            # если не установлено, установить текущего пользователя, который создал продукт
            super().save(*args, **kwargs)

    def get_absolute_url(self) -> str:
        """Метод для получения URL страницы с подробной информацией о
        товаре."""
        return reverse("store:product_detail", args=[self.slug, self.id])

    def __str__(self) -> str:
        return self.name


class Comment(models.Model):
    """Комментарий к товару."""

    product: Product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user: User = models.ForeignKey(User, on_delete=models.CASCADE)
    text: str = models.TextField(max_length=200)
    created_at: models.DateTimeField = models.DateTimeField(auto_now_add=True)
    updated_at: models.DateTimeField = models.DateTimeField(auto_now=True)
    active: bool = models.BooleanField(default=True)

    class Meta:
        ordering: list = ["-created_at"]
        indexes: list = [
            models.Index(fields=["product"]),
            models.Index(fields=["user"]),
            models.Index(fields=["active"]),
            models.Index(fields=["created_at"]),
        ]

    def get_absolute_url(self) -> str:
        """Метод для получения URL страницы с подробной информацией о
        товаре."""
        return reverse(
            "store:product_detail", args=[self.product.slug, self.product.id]
        )

    def __str__(self) -> str:
        return f"{self.user.username} - {self.product.name}"

farmer/store/views.py
"""Этот модуль предоставляет представления и вспомогательные функции для
приложения магазина.

Классы:
     CommentCreateView: представление для создания нового комментария.
     CommentUpdateView: представление для обновления существующего комментария.
     CommentDeleteView: представление для удаления комментария.
     Search: представление для поиска продуктов.

Функции:
     sellerprofile: представление для отображения страницы профиля продавца.
     rating: вид для оценки продавца.
"""

from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import (HttpRequest, HttpResponse, JsonResponse)
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.views.decorators.http import require_POST
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView

from cart.forms import CartAddProductForm
from users.models import Buyer, Ratings, Seller

from .models import Category, Comment, Product
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

def home(request: HttpRequest, category_slug=None) -> HttpResponse:
    """Представление главной страницы."""
    category = None
    categories = Category.objects.all()
    # Фильтрация продуктов в зависимости от группы пользователя.
    if request.user.groups.filter(name="Sellers").exists():
        products = Product.objects.filter(seller=request.user)
    else:
        products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)

    paginator = Paginator(products, 5)
    page = request.GET.get("page")
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
        
    

    return render(
        request,
        "store/products/home.html",
        {"categories": categories, "products": products, "category": category},
    )


def product_detail(request: HttpRequest, slug: str, id: int) -> HttpResponse:
    """Представление для страницы продукта."""
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    # Форма для добавления продукта в корзину
    cart_product_form = CartAddProductForm()
    comments = product.comment_set.all()
    if request.user.groups.filter(name="Sellers").exists():
        return render(
            request,
            "store/products/seller_product_detail.html",
            {
                "product": product,
                "comments": comments,
            },
        )
    else:
        return render(
            request,
            "store/products/product_detail.html",
            {
                "product": product,
                "cart_product_form": cart_product_form,
                "comments": comments,
            },
        )


@login_required(login_url="users:login")
@require_POST
def product_like(request: HttpRequest) -> JsonResponse:
    """Добавление/удаление лайка продукта."""
    # Получаем id продукта и действие (лайк или удаление лайка)
    product_id = request.POST.get("id")
    action = request.POST.get("action")
    # Если переданы оба параметра, то пытаемся найти продукт по id и выполнить действие
    if product_id and action:
        try:
            product = Product.objects.get(id=product_id)
            if action == "like":
                product.users_like.add(request.user)
            else:
                product.users_like.remove(request.user)
            return JsonResponse({"status": "ok"})
        except product.DoesNotExist:
            pass
    # Если что-то пошло не так, возвращаем ошибку
    return JsonResponse({"status": "error"})


class CommentCreateView(CreateView):
    """Отображает форму создания комментария."""

    model = Comment
    fields = ["text"]

    def form_valid(self, form) -> HttpResponse:
        """Сохраняет комментарий, привязывая его к пользователю и продукту, и
        возвращает HTTP-ответ."""

        # Получаем значения slug и id из kwargs и используем их для связи с продуктом
        form.instance.product = Product.objects.get(
            slug=self.kwargs["slug"], id=self.kwargs["id"]
        )

        # Сохраняем пользователя
        form.instance.user = User.objects.get(id=self.request.user.id)

        return super().form_valid(form)


class CommentUpdateView(UpdateView):
    """Отображает форму редактирования комментария."""

    model = Comment
    fields = ["text"]


class CommentDeleteView(DeleteView):
    """Отображает форму удаления комментария."""

    model = Comment

    def get_success_url(self, **kwargs) -> str:
        """Возвращает URL для перенаправления после успешного удаления
        комментария."""

        return reverse_lazy(
            "store:product_detail",
            kwargs={"slug": self.object.product.slug,
                    "id": self.object.product.id},
        )


@login_required(login_url="users:login")
def sellerprofile(request: HttpRequest, id: int) -> HttpResponse:
    """Отображает страницу профиля продавца."""

    user = get_object_or_404(User, id=id)

    profile = user.seller
    products = user.seller_products.all()
    rating = profile.ratings_set.filter(buyer=request.user.buyer)
    seller_lat = profile.get_real_address()[0]
    seller_lon = profile.get_real_address()[1]

    return render(
        request,
        "store/profile/seller_profile.html",
        {"profile": profile, "products": products, "rating": rating, "seller_lat": seller_lat, "seller_lon": seller_lon},
    )


@login_required(login_url="users:login")
@require_POST
def rating(request: HttpRequest) -> JsonResponse:
    """Обрабатывает POST-запрос с рейтингом и идентификатором продавца и
    сохраняет рейтинг.

    Возвращает JSON-ответ, указывающий на успех операции.
    """

    rating_num = request.POST.get("rating")
    seller_id = request.POST.get("seller_id")

    if rating_num and seller_id:
        seller = get_object_or_404(Seller, id=seller_id)

        rating, create = Ratings.objects.get_or_create(
            buyer=request.user.buyer, seller=seller
        )

        if rating.rating == 0:
            rating.rating = rating_num
            rating.save()

        return JsonResponse({"success": True})

    # Если что-то пошло не так, возвращаем ошибку
    return JsonResponse({"status": "error"})


class Search(ListView):
    """Отображает результаты поиска продуктов.

    Если по запросу ничего не найдено, перенаправляет на главную
    страницу магазина.
    """

    template_name = "store/products/home.html"
    context_object_name = "products"

    def get_queryset(self):
        """Возвращает список продуктов, соответствующих поисковому запросу."""

        products = Product.objects.filter(
            name__icontains=self.request.GET.get("q"))
        
        return products

    def get_context_data(self, *, object_list=None, **kwargs):
        """Добавляет поисковый запрос в контекст шаблона."""

        context = super().get_context_data(**kwargs)
        context["q"] = self.request.GET.get("q")
        return context

    def render_to_response(self, context, **response_kwargs):
        """Отображает ответ и перенаправляет на главную страницу магазина, если
        результаты поиска не найдены."""

        if not Search.get_queryset(self) or not context["q"]:
            return redirect("store:home")
        else:
            return super().render_to_response(context, **response_kwargs)

farmer/store/templates/store/products/home.html
{% extends "store/base.html" %}
{% load static %}
{% block title %}
{% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}
{%block search%}
<div class = 'search'>
<form action="{% url 'store:search' %}" method="get">
    <input type="text", type="search", name="q", placeholder="search">
    <button type="submit">Найти</button>    
</form>
</div>
{%endblock%}

{% block content %}
<div id="sidebar">
    <h3>Categories</h3>
    <ul>
        <li {% if not category %}class="selected" {% endif %}>
            <a href="{% url "store:home" %}">All</a>
        </li>
        {% for c in categories %}
        <li {% if category.slug == c.slug %}class="selected" {% endif %}>
            <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
        </li>
        {% endfor %}
    </ul>
</div>
<div id="main" class="product-list">
    <h1>{% if category %}{{ category.name }}{% else %}Products
        {% endif %}</h1>
    {% for product in products %}
    <div class="item">
        <a href="{{ product.get_absolute_url }}">
            <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
        </a>
        <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
        <br>
        ${{ product.price }}
    </div>
    {% endfor %}
</div>
{% include "pagination.html" with page=products %}
{% endblock %}

farmer/store/templates/store/products/product_detail.html
{% extends "store/base.html" %}
{% load static %}
{% block title %}
{{ product.name }}
{% endblock %}
{% block content %}
<div class="product-detail">
    <img src="{% if product.image %}{{ product.image.url }}{% else %}
 {% static "img/no_image.png" %}{% endif %}">
    <h1>{{ product.name }}</h1>
    <h2>
        <a href="{{ product.category.get_absolute_url }}">
            {{ product.category }}
        </a>
    </h2>
    <p class="price">${{ product.price }}</p>
    <form action="{% url "cart:cart_add" product.id %}" method="post">
        {{ cart_product_form }}
        {% csrf_token %}
        <input type="submit" value="Add to cart">
    </form>
    {{ product.description|linebreaks }}
    {% if user.is_authenticated%}
   <p> <a href="{% url 'store:profile'  product.seller.id %}" class= "button"> Seller profile</a></p>
   {%endif%}
</div>


{% if user.is_authenticated %}
{% with total_likes=product.users_like.count users_like=product.users_like.all %}
  <div class="image-info">
    <div>
      <span class="count">
        <span class="total">{{ total_likes }}</span>
        like{{ total_likes|pluralize }}
      </span>
      
      <a href="#" data-id="{{ product.id }}" data-action="{% if request.user in users_like %}un{% endif %}like" class="like button">
        {% if request.user not in users_like %}
          Like
        {% else %}
          Unlike
        {% endif %}
      </a>
    </div>
    {% endwith %}
    <div>
      {% endif %}
      {% if user.is_authenticated %}
  
      <a href="{% url 'store:comment-add' product.slug  product.id %} "class= "button">Add comment</a>
      {%endif%}
  </div>
<ul class="comment-list">
  <h3>Comments</h3>
    {% for comment in comments %}

    <li class="comment">
        <h4>{{ comment.user.username }}</h4>
        <p>{{ comment.text }}</p>
        <div class="meta">{{ comment.created_at|date }}</div>
   
    {% if user.username == comment.user.username%}
    <a href="{% url 'store:comment-delete' comment.id %}">Delete comment</a>
    <a href="{% url 'store:comment-update' comment.id %}">Edit comment</a>
    {%endif%}
    {% empty %}
</li>
    <li>No comments yet.</li>
    {% endfor %}
</ul>


{% endblock %}
{% block domready %}
  const url = '{% url 'store:like' %}';
  var options = {
    method: 'POST',
    headers: {'X-CSRFToken': csrftoken},
    mode: 'same-origin'
  }

  document.querySelector('a.like')
          .addEventListener('click', function(e){
    e.preventDefault();
    var likeButton = this;

    // add request body
    var formData = new FormData();
    formData.append('id', likeButton.dataset.id);
    formData.append('action', likeButton.dataset.action);
    options['body'] = formData;

    // send HTTP request
    fetch(url, options)
    .then(response => response.json())
    .then(data => {
      if (data['status'] === 'ok')
      {
        var previousAction = likeButton.dataset.action;

        // toggle button text and data-action
        var action = previousAction === 'like' ? 'unlike' : 'like';
        likeButton.dataset.action = action;
        likeButton.innerHTML = action;

        // update like count
        var likeCount = document.querySelector('span.count .total');
        var totalLikes = parseInt(likeCount.innerHTML);
        likeCount.innerHTML = previousAction === 'like' ? totalLikes + 1 : totalLikes - 1;
      }
    })
  });
{% endblock %}

farmer/store/templates/store/products/seller_product_detail.html
{% extends "store/base.html" %}
{% load static %}
{% block title %}
{{ product.name }}
{% endblock %}
{% block content %}
<div class="product-detail">
    <img src="{% if product.image %}{{ product.image.url }}{% else %}
 {% static "img/no_image.png" %}{% endif %}">
    <h1>{{ product.name }}</h1>
    <h2>
        <a href="{{ product.category.get_absolute_url }}">
            {{ product.category }}
        </a>
    </h2>
    <p class="price">${{ product.price }}</p>
   
    {{ product.description|linebreaks }}
  <br>
  <br>
  <br>
</div>




   
 
<ul class="comment-list">
    {% for comment in comments %}

    <li class="comment">
        <h4>{{ comment.user.username }}</h4>
        <p>{{ comment.text }}</p>
        <div class="meta">{{ comment.created_at|date }}</div>
   
    {% if user.username == comment.user.username%}
    <a href="{% url 'store:comment-delete' comment.id %}">Delete comment</a>
    <a href="{% url 'store:comment-update' comment.id %}">Edit comment</a>
    {%endif%}
    {% empty %}
</li>
    <li>No comments yet.</li>
    {% endfor %}
</ul>


{% endblock %}
{% block domready %}
 
{% endblock %}